### ISSUE TITLE
Does not work with org-ql:

### ISSUE THREAD

**Issue by egh** [minad/org-modern#85] opened 2022-08-09 16:35 UTC
When using [org-super-agenda](https://github.com/alphapapa/org-super-agenda), `TODO` keywords do not display properly in the agenda, but `DONE` keywords do. I think this is because `org-todo-keywords-for-agenda` does not appear to be set.

![image](https://user-images.githubusercontent.com/22718/183707784-c88f68e9-6513-4b72-a0b9-d3de9e72a740.png)

**Comment by minad** [comment] 2022-08-09 19:32
Maybe @alphapapa can help here?

**Comment by alphapapa** [comment] 2022-08-10 13:47
I don't see how org-super-agenda could be related to this problem.

**Comment by egh** [comment] 2022-08-10 17:02
My mistake, this seems to be a problem with `org-ql`. Apologies for not creating a minimum reproducible example, which would revealed the source of the problem.

Create `~/org/test.org/`

```
* TODO my project
SCHEDULED: <2022-08-10 Wed>
```

run `emacs -q`

and evaluate:

```
(setq package-native-compile t
      package-archives
      '(("melpa" . "https://melpa.org/packages/")))
(package-initialize)
(package-refresh-contents)
(package-install 'use-package)
(require 'use-package)
(use-package org-modern
  :ensure t
  :config (global-org-modern-mode))
(use-package org-ql :ensure t)
(setq org-agenda-files (list org-directory)
      org-agenda-custom-commands
      `(("t" "test agenda"
         ((agenda)
          (org-ql-block '(and (or (todo "STARTED") (todo "TODO")) (not (scheduled)) (not (deadline))))))))
```

Run `M-x org-agenda` then `t`

![image](https://user-images.githubusercontent.com/22718/183973183-c7df12f1-2d31-49ef-b3b2-04992a6bd25f.png)

**Comment by minad** [comment] 2022-08-11 00:20
This is probably a duplicate of #26, an upstream issue.

**Closed by minad** 2022-08-11 00:20 UTC

**Comment by egh** [comment] 2022-08-11 15:45
@minad Thank you!

**Comment by minad** [comment] 2024-07-21 21:23
Fixed in https://github.com/minad/org-modern/commit/6550abc8c7b059cfa8b1653c280dde030787a6e7
