### ISSUE TITLE
org-modern-agenda breaks setting correct face for org-done-keywords in org-ql-agenda

### ISSUE THREAD

**Issue by ParetoOptimalDev** [minad/org-modern#126] opened 2023-04-14 01:31 UTC
I think it somehow overwrites the faces with org-done with org-todo?

I proved this to myself by removing org-modern from the org-finalize-hook and observing that org-ql-agenda used the org-done face.

I aslo reported this there: https://github.com/alphapapa/org-ql/issues/347

**Comment by minad** [comment] 2023-04-14 09:06
This is a duplicate of #85. Unfortunately the problem boils down to an upstream issue in Org itself #26.

**Closed by minad** 2023-04-14 09:06 UTC
