### ISSUE TITLE
Table separators uses default font width, which may not match `org-table`

### ISSUE THREAD

**Issue by WJCFerguson** [minad/org-modern#99] opened 2022-10-29 13:49 UTC
My `org-table` is a different width from `default` face (I'm using package `org-variable-pitch` which is probably why, with fixed-pitch on `org-table` face).

I see `org-modern--pre-redisplay` uses `(default-font-width)` to set the width of the divider characters.  That gives 14, while my `org-table` is width 12.  The result is:

![image](https://user-images.githubusercontent.com/3020220/198834470-f05c4735-9cf5-469e-911b-be7d844e3e46.png)

[something is also screwey with the height change not being respected; I'm built from very recent Emacs `master`, so `29.0.50`]

With my ham-fisted hacking I can 'fix' it by getting the width from the `org-table` face instead of `(default-font-width)`, but I have no idea if there's an easier way or if this will break down in some circumstances:

``` elisp
(defun face-width (face)
  "Return the width in pixels of the FACE font."
  ;; logic cut/paste from `default-font-width'
  (let* ((info (font-info (face-font face)))
	 (width (aref info 11)))
    (if (> width 0)
	width
      (aref info 10))))

(defun org-modern--pre-redisplay (_)
  "Compute font parameters before redisplay."
  (when-let (box (and org-modern-label-border
                      (face-attribute 'org-modern-label :box nil t)))
    (unless (equal (and (listp box) (plist-get box :color))
                   (face-attribute 'default :background nil t))
      (org-modern--update-label-face)))
  (setf org-modern--table-sp-width (face-width 'org-table) ;; <<< changed from (default-font-width)
        (cadr org-modern--table-overline) (face-attribute 'org-table :foreground nil t)))
```

**Comment by minad** [comment] 2022-10-29 20:29
Sounds like a good idea to take the width of the org-table face instead of the default face. I will push a fix. Thanks!

(But regarding more complicated scenarios, variable pitch etc, there won't be a way around #5. It's on my long term roadmap.)

**Comment by minad** [comment] 2022-10-30 10:09
Hey @WJCFerguson, I experimented with three ways to solve the issue.

1. Your patch

2. Using `face-remapping-alist`

~~~ elisp
  (setq org-modern--table-sp-width (face-width 'org-table)
        (let ((face-remapping-alist `((default org-table)
                                      ,@face-remapping-alist)))
          (default-font-width)))
~~~

3. Using `window-font-width`

~~~ elisp
(setq org-modern--table-sp-width (window-font-width nil 'org-table))
~~~

While all three solutions solve the issue you are facing, these patches introduce a regression regarding font resizing (#69, #75). The commands `text-scale-adjust`/`-increase`/`-decrease` will then break the alignment of the horizontal lines. Since I consider text scaling as more important, I  close this issue as wontfix. If you figure out a better solution, I am happy to hear and merge a patch. But it seems we won't get by with such a simple solution.

**Closed by minad** 2022-10-30 10:09 UTC

**Comment by minad** [comment] 2022-10-30 10:14
I should add - our best bet is probably to find a solution based on (2) if we use a more complicated manipulation of the `face-remapping-alist` which ensures that both the remapping to `org-table` and the remapping of `default` (due to text scaling) are taken into account. Maybe you could take a look at how the `face-remapping-alist` looks like if you use `org-variable-pitch` and rescale the text.

**Comment by WJCFerguson** [comment] 2022-10-30 16:31
Thank you for looking at this, it's obviously tricky to cover all the bases.

I'll continue to investigate, but I suspect I'll just change my config so the faces are the same width.  I define a larger point-size variable pitch face at my desktop environment level, inherited by Emacs, because it comes through a comparable viewing size to the monospace.

Looks like finding out what `face-remapping-alist` is all about is in my future ;).

**Comment by minad** [comment] 2022-10-30 17:01
On 10/30/22 17:31, James Ferguson wrote:
> Thank you for looking at this, it's obviously tricky to cover all the bases.
> 
> I'll continue to investigate, but I suspect I'll just change my config
> so the faces are the same width. I define a larger point-size variable
> pitch face at my desktop environment level, inherited by Emacs, because
> it comes through a comparable viewing size to the monospace.
> 
> Looks like finding out what |face-remapping-alist| is all about is in my
> future ;).

If you figure out something, please let me know. It would be nice to
have that fixed, such that org-modern interacts well with
org-variable-pitch. But from my experience, face width computations in
the presence of a non-nil face-remapping-alist are tricky. I've had
similar issues in my Corfu package.

**Comment by fredericgiquel** [comment] 2022-11-04 19:28
The following way to compute `org-modern--table-sp-width` seems to solve the issue without regression regarding font resizing:
```elisp
(setq org-modern--table-sp-width
        (let ((face-remapping-alist
               `((default (:inherit org-table :height ,(expt text-scale-mode-step text-scale-mode-amount))))))
          (default-font-width)))
```

**Comment by minad** [comment] 2022-11-04 20:08
Yes, this goes in the right direction. However it is not an ideal
solution since it neglects other remappings. Therefore we also have to
replicate the text-scale remapping and height computation here.

**Comment by fredericgiquel** [comment] 2022-11-05 10:22
This one keeps other remappings and does not recompute height from text-scale variables:

```elisp
(setq org-modern--table-sp-width
        (let* ((default-height (cadr (assoc :height (assoc 'default face-remapping-alist))))
               (face-remapping-alist `((default
                                         ,(append '(:inherit org-table) (when default-height `(:height ,default-height)))
                                         default)
                                       ,@face-remapping-alist)))
          (default-font-width)))
```

**Comment by minad** [comment] 2022-11-09 21:21
@fredericgiquel 

Well, this is not much better since we have to lookup the text-scale remapping. I wonder if there is a better way where we can reuse the existing remappings as is (without :height special casing etc) and just merge in org-table inheritance somehow. Unfortunately I don't know enough about the remapping mechanism (yet).

**Comment by fredericgiquel** [comment] 2024-07-26 11:38
This issue has indeed been fixed by commit 1074133d9dd1ce4eb6c9ab1d1dbc7b78b3d8733b.
But with my configuration (Emacs 29.4), the commit 0798c12bb7e4d8adbeb79605683fc51f1c5a4f2e reintroduced the problem.

**Comment by minad** [comment] 2024-07-26 17:35
What is going on specifically in your configuration? I think https://github.com/minad/org-modern/commit/0798c12bb7e4d8adbeb79605683fc51f1c5a4f2e looks like the "correct" way to add the remapping. But let's try the another remapping in https://github.com/minad/org-modern/commit/144ccef2196043955cf750753b8d2febc868b312. I am really stabbing in the dark. How does the `face-remapping-alist` look for you?

**Comment by fredericgiquel** [comment] 2024-07-26 20:25
The problem is solved for me with the last commit. Thanks.
The behaviour is the same with my complete configuration or a minimal one with only 2 packages and the following `init.el`:
```emacs-lisp
(use-package mixed-pitch
  :init
  (set-face-attribute 'default nil :family "Hack")
  (set-face-attribute 'fixed-pitch nil :family "Hack")
  (set-face-attribute 'variable-pitch nil :family "FiraGo")
  :hook (org-mode . mixed-pitch-mode))

(use-package org-modern
  :custom
  (org-pretty-entities t)
  :config
  (global-org-modern-mode))
```

The value of `face-remapping-alist` inside the let expression is:
- `((default org-table (:family FiraGo :weight unspecified) default default))` with commit 0798c12bb7e4d8adbeb79605683fc51f1c5a4f2e
- `((default org-table (:family FiraGo :weight unspecified) default) (org-verbatim (:family Hack :weight regular) org-verbatim) (org-table (:family Hack :weight regular) org-table) (org-meta-line (:family Hack :weight regular) org-meta-line) (org-formula (:family Hack :weight regular) org-formula) (org-checkbox (:family Hack :weight regular) org-checkbox) (org-latex-and-related (:family Hack :weight regular) org-latex-and-related) (org-indent (:family Hack :weight regular) org-indent) (org-code (:family Hack :weight regular) org-code) (org-document-info-keyword (:family Hack :weight regular) org-document-info-keyword) (org-block-end-line (:family Hack :weight regular) org-block-end-line) (org-block-begin-line (:family Hack :weight regular) org-block-begin-line) (org-block (:family Hack :weight regular) org-block) (mu4e-compose-header-face (:family Hack :weight regular) mu4e-compose-header-face) (mu4e-compose-separator-face (:family Hack :weight regular) mu4e-compose-separator-face) (mu4e-contact-face (:family Hack :weight regular) mu4e-contact-face) (mu4e-link-face (:family Hack :weight regular) mu4e-link-face) (mu4e-header-value-face (:family Hack :weight regular) mu4e-header-value-face) (mu4e-header-key-face (:family Hack :weight regular) mu4e-header-key-face) (message-header-other (:family Hack :weight regular) message-header-other) (message-header-subject (:family Hack :weight regular) message-header-subject) (message-header-xheader (:family Hack :weight regular) message-header-xheader) (message-header-newsgroups (:family Hack :weight regular) message-header-newsgroups) (message-header-cc (:family Hack :weight regular) message-header-cc) (message-header-to (:family Hack :weight regular) message-header-to) (message-header-name (:family Hack :weight regular) message-header-name) (markdown-math-face (:family Hack :weight regular) markdown-math-face) (markdown-language-keyword-face (:family Hack :weight regular) markdown-language-keyword-face) (markdown-language-info-face (:family Hack :weight regular) markdown-language-info-face) (markdown-inline-code-face (:family Hack :weight regular) markdown-inline-code-face) (markdown-gfm-checkbox-face (:family Hack :weight regular) markdown-gfm-checkbox-face) (markdown-code-face (:family Hack :weight regular) markdown-code-face) (line-number-minor-tick (:family Hack :weight regular) line-number-minor-tick) (line-number-major-tick (:family Hack :weight regular) line-number-major-tick) (line-number-current-line (:family Hack :weight regular) line-number-current-line) (line-number (:family Hack :weight regular) line-number) (font-lock-variable-name-face (:family Hack :weight regular) font-lock-variable-name-face) (font-lock-type-face (:family Hack :weight regular) font-lock-type-face) (font-lock-string-face (:family Hack :weight regular) font-lock-string-face) (font-lock-regexp-grouping-construct (:family Hack :weight regular) font-lock-regexp-grouping-construct) (font-lock-regexp-grouping-backslash (:family Hack :weight regular) font-lock-regexp-grouping-backslash) (font-lock-preprocessor-face (:family Hack :weight regular) font-lock-preprocessor-face) (font-lock-negation-char-face (:family Hack :weight regular) font-lock-negation-char-face) (font-lock-keyword-face (:family Hack :weight regular) font-lock-keyword-face) (font-lock-function-name-face (:family Hack :weight regular) font-lock-function-name-face) (font-lock-doc-face (:family Hack :weight regular) font-lock-doc-face) (font-lock-constant-face (:family Hack :weight regular) font-lock-constant-face) (font-lock-comment-delimiter-face (:family Hack :weight regular) font-lock-comment-delimiter-face) (font-lock-builtin-face (:family Hack :weight regular) font-lock-builtin-face) (font-latex-sectioning-5-face (:family Hack :weight regular) font-latex-sectioning-5-face) (font-latex-warning-face (:family Hack :weight regular) font-latex-warning-face) (font-latex-sedate-face (:family Hack :weight regular) font-latex-sedate-face) (font-latex-math-face (:family Hack :weight regular) font-latex-math-face) (diff-removed (:family Hack :weight regular) diff-removed) (diff-hunk-header (:family Hack :weight regular) diff-hunk-header) (diff-header (:family Hack :weight regular) diff-header) (diff-function (:family Hack :weight regular) diff-function) (diff-file-header (:family Hack :weight regular) diff-file-header) (diff-context (:family Hack :weight regular) diff-context) (diff-added (:family Hack :weight regular) diff-added) (default (:family FiraGo :weight unspecified) default)` with last commit 144ccef2196043955cf750753b8d2febc868b312
